#!/usr/bin/env python3
"""Replace the pinyin GeoNames garbage (1700 host-wanted rows) with real,
well-known attractions collected from Wikidata via fetch_places.py.

Input:  scripts/seed/places_china.json  (produced by fetch_places.py)
Output: scripts/seed/seed_china_real.sql

Rules:
  * drop transit hubs (stations/airports) — nobody hosts a railway station.
  * skip QIDs already owned by real seeded spaces, so we never clobber them.
  * every new row is public, resident, host_user_id NULL, tag '主理人招募中'.
  * guide prose is the same honest, template-free-of-facts text as the global
    seed (no invented hours/prices/phones).
The file starts by deleting the old pinyin batch (host_user_id NULL AND
tag_zh='主理人招募中' with an ASCII-only name_zh), so re-running is safe.
"""
import json
import os

import make_seed_sql as m

HERE = os.path.dirname(os.path.abspath(__file__))
AUTHOR_ID = "00000000-0000-0000-0000-000000000001"
AUTHOR_NAME = "inspace 编辑部"


def is_ascii(s):
    return all(ord(c) < 128 for c in (s or ""))


def owned_qids():
    """QIDs already represented by the global (non-recruitment) seed."""
    places = json.load(open(os.path.join(HERE, "places.json")))
    return {p["qid"] for p in places}


def main():
    places = json.load(open(os.path.join(HERE, "places_china.json")))
    owned = owned_qids()

    kept = []
    seen = set()
    for p in places:
        if p["space_type"] == "transit":
            continue
        if p["qid"] in owned or p["qid"] in seen:
            continue
        seen.add(p["qid"])
        kept.append(p)

    lines = [
        "-- Generated by scripts/seed/seed_china_real.py. Do not edit by hand.",
        "-- Real attractions (Wikidata) replacing the pinyin GeoNames batch.",
        "BEGIN;",
        "-- Remove the old pinyin host-wanted rows (ASCII name_zh is the tell).",
        "DELETE FROM guides g USING spaces s",
        " WHERE g.space_id = s.id AND s.host_user_id IS NULL",
        "   AND s.tag_zh = '主理人招募中' AND s.name_zh ~ '^[[:ascii:]]+$';",
        "DELETE FROM spaces s",
        " WHERE s.host_user_id IS NULL",
        "   AND s.tag_zh = '主理人招募中' AND s.name_zh ~ '^[[:ascii:]]+$';",
    ]

    for p in kept:
        space_id = m.det_uuid("space", p["qid"])
        guide_id = m.det_uuid("guide", p["qid"])
        g = m.build_guide(p)
        desc_zh = f"{p['country_zh']}·{p['city']}的{p['name_zh']}空间，正在招募主理人。攻略、现场提问和讨论都在这里。"
        desc_en = f"A space for {p['name_en']} in {p['city_en']}, {p['country']}, looking for a local host. Guides, questions and live discussion."

        lines.append(
            "INSERT INTO spaces (id, name_zh, name_en, space_type, country, province, city, district, spot_name, "
            "lat, lng, is_public, password_hash, duration_hours, status, resident, resident_days, "
            "tag_zh, tag_en, description_zh, description_en, creator_id, host_user_id) VALUES ("
            f"{m.q(space_id)}, {m.q(p['name_zh'])}, {m.q(p['name_en'])}, '{p['space_type']}', "
            f"{m.q(p['country'])}, {m.q(p['province'])}, {m.q(p['city'])}, NULL, {m.q(p['name_zh'])}, "
            f"{p['lat']}, {p['lng']}, TRUE, {m.q(m.SEED_HASH)}, 24, 'active', TRUE, 3650, "
            f"'主理人招募中', 'Host wanted', {m.q(desc_zh)}, {m.q(desc_en)}, {m.q(AUTHOR_ID)}, NULL"
            ") ON CONFLICT (id) DO UPDATE SET "
            "name_zh = EXCLUDED.name_zh, name_en = EXCLUDED.name_en, space_type = EXCLUDED.space_type, "
            "country = EXCLUDED.country, province = EXCLUDED.province, city = EXCLUDED.city, "
            "spot_name = EXCLUDED.spot_name, lat = EXCLUDED.lat, lng = EXCLUDED.lng, "
            "tag_zh = '主理人招募中', tag_en = 'Host wanted', "
            "description_zh = EXCLUDED.description_zh, description_en = EXCLUDED.description_en, "
            "status = 'active', resident = TRUE, is_public = TRUE, host_user_id = NULL, updated_at = now();"
        )

        sections_json = json.dumps(g["sections"], ensure_ascii=False)
        lines.append(
            "INSERT INTO guides (id, title_zh, title_en, summary_zh, summary_en, content_zh, content_en, "
            "guide_type, category, province, city, district, spot_name, status, featured, author_id, author_name, space_id, sections) VALUES ("
            f"{m.q(guide_id)}, {m.q(g['title_zh'])}, {m.q(g['title_en'])}, {m.q(g['summary_zh'])}, {m.q(g['summary_en'])}, "
            f"{m.q(g['content_zh'])}, {m.q(g['content_en'])}, 'attraction', 'host-wanted', "
            f"{m.q(p['province'])}, {m.q(p['city'])}, NULL, {m.q(p['name_zh'])}, 'published', FALSE, "
            f"{m.q(AUTHOR_ID)}, {m.q(AUTHOR_NAME)}, {m.q(space_id)}, {m.q(sections_json)}::jsonb"
            ") ON CONFLICT (id) DO UPDATE SET "
            "title_zh = EXCLUDED.title_zh, title_en = EXCLUDED.title_en, "
            "summary_zh = EXCLUDED.summary_zh, summary_en = EXCLUDED.summary_en, "
            "content_zh = EXCLUDED.content_zh, content_en = EXCLUDED.content_en, "
            "category = 'host-wanted', sections = EXCLUDED.sections, status = 'published', updated_at = now();"
        )

    lines.append("COMMIT;")
    out = os.path.join(HERE, "seed_china_real.sql")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"kept {len(kept)} real attractions -> {out}")


if __name__ == "__main__":
    main()
